steps:
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "${_ENV}", "./backend/.env"]  # copy langsung ke folder backend

  - name: "gcr.io/cloud-builders/docker"
    dir: "backend"  # <- penting agar Dockerfile terbaca
    args: ["build", "-t", "gcr.io/$PROJECT_ID/rmjrentcar", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/rmjrentcar"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "rmjrentcar",
        "--image",
        "gcr.io/$PROJECT_ID/rmjrentcar",
        "--port",
        "5000",
        "--region",
        "asia-southeast2",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "3000s"
