steps:
  - name: "gcr.io/cloud-builders/docker"
    dir: "frontend"  # artinya semua proses build dilakukan dari /workspace/frontend
    args: ["build", "-t", "gcr.io/$PROJECT_ID/frontend", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/frontend"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "frontend",
        "--image",
        "gcr.io/$PROJECT_ID/frontend",
        "--port",
        "80",
        "--region",
        "asia-southeast2",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]

options:
  logging: CLOUD_LOGGING_ONLY
  
timeout: "3000s"
